### ISSUE TITLE
Failed to count if dir name is Chinese

### ISSUE THREAD

**Issue by jinq0123** [MorganZhang100/line-counter#1]
Failed to count if dir name is Chinese:
<pre>
D:\Jinq\moba手游最后一战\[moba手游]最后一战\[moba手游]最后一战\Server>line
Search in D:\Jinq\moba手游最后一战\[moba手游]最后一战\[moba手游]最后一战\Server\

file count: 0
line count: 0
</pre>

I moved dir to d:\temp and got the count.

**Comment by MorganZhang100** [comment]
Thanks for using this software and reporting this bug to me.
Actually, it's not because of the Chinese dir name. It's because there is a special character '[' in the file name. Your example input is very helpful.
I have fixed this bug. Please update your line-counter through pip. Please let me know if you have any questions.

**Comment by jinq0123** [comment]
:)

**Comment by jinq0123** [comment]
Still no result.
I found select_filter() returns False because
```fnmatch.fnmatch("d:\\temp\\abc[d]\\DefLogging.h", "d:\\temp\\abc[d]\\*")```
 returns False.

**Comment by MorganZhang100** [comment]
are you using 0.7.4 version of the line-counter? 
You can get the version by running `line-counter --version`

**Comment by jinq0123** [comment]
<pre>
E:\temp\ab[c]>line
Search in E:\temp\ab[c]\
file count: 0
line count: 0

E:\temp\ab[c]>line --version
line 0.7.4
</pre>

<pre>
E:\temp\ab[c]>cd ..

E:\temp>xcopy /i ab[c] abc
ab[c]\cmd_test.h
复制了 1 个文件

E:\temp>cd abc

E:\temp\abc>line
Search in E:\temp\abc\
file count: 1
line count: 21

</pre>
